### ISSUE TITLE
Sample data for formation

### ISSUE THREAD

**Issue by NeverGiveU** [hahapz/ImageWarping#1]
hi! Could you please share you sample data as well as the testing results?

**Comment by ZhuangPeng97** [comment]
> hi! Could you please share you sample data as well as the testing results?

Hi, I've just done some tests, and here are some of the results, hope it can be helpful!
[data.zip](https://github.com/hahapz/ImageWarping/files/4786873/data.zip)

**Comment by NeverGiveU** [comment]
thank U very much! well, recently i was trying to implement this algorithm with python based on your codes. it greatly mattered to my understanding to the algorithm described in the paper. thanks a lot again. now i make sure that while there were some errs in my implementation and the results are strange. i will further correct them in these days.

**Comment by NeverGiveU** [comment]
hi, could u please share us the version of opencv u have used for this code?

**Comment by ZhuangPeng97** [comment]
> hi, could u please share us the version of opencv u have used for this code?

I use opencv–3.4.6 and windows10.Good luck！

**Comment by NeverGiveU** [comment]
thanks a lot, now i can re-implement it with `python` now.
